[workspace]
members = [
    "whale",
    "whale-tui",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
readme = "README"
license = "MIT OR Apache-2.0"
repository = "https://github.com/alvarobartt/whale"
authors = ["Alvaro Bartolome <alvarobartt@gmail.com>"]
