[workspace]
members = ["bluewhale"]
resolver = "3"

[workspace.package]
version = "0.0.1"
edition = "2024"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/alvarobartt/bluewhale"
authors = ["Alvaro Bartolome <alvarobartt@gmail.com>"]
